#lang racket

(define (make-account balance)
  (define (withdraw amount)
    (if (>= balance amount)
        (begin (set! balance (- balance amount))
               balance)
        ("Insufficient funds")))
  (define (deposit amount)
    (set! balance (+ balance amount))
    balance)
  (define (dispatch op)
    (cond ((eq? op 'withdraw) withdraw)
          ((eq? op 'deposit) deposit)
          (else (error "Unknown request -- MAKE-ACCOUT" op))))
  dispatch)